services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - discovery-type=single-node
      - xpack.license.self_generated.type=trial
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./http_ca.crt:/usr/share/elasticsearch/config/certs/http_ca.crt
      - ./transport.p12:/usr/share/elasticsearch/config/certs/transport.p12
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 100

  fastapi:
    build: .
    container_name: fastapi
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - ELASTIC_HOST=elasticsearch:9200

networks:
  elastic:
    driver: bridge